// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schedule.Infrastructure.Database.Context;

#nullable disable

namespace Schedule.Infrastructure.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    [Migration("20251201150322_Reformed-database_model")]
    partial class Reformeddatabase_model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Schedule.Domain.Entities.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayId"));

                    b.Property<int?>("AssignedMeal")
                        .HasColumnType("int");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DayId");

                    b.HasIndex("AssignedMeal");

                    b.ToTable("Days", (string)null);

                    b.HasData(
                        new
                        {
                            DayId = 1,
                            DayName = "monday"
                        },
                        new
                        {
                            DayId = 2,
                            DayName = "tuesday"
                        },
                        new
                        {
                            DayId = 3,
                            DayName = "wednesday"
                        },
                        new
                        {
                            DayId = 4,
                            DayName = "thursday"
                        },
                        new
                        {
                            DayId = 5,
                            DayName = "friday"
                        },
                        new
                        {
                            DayId = 6,
                            DayName = "saturday"
                        },
                        new
                        {
                            DayId = 7,
                            DayName = "sunday"
                        });
                });

            modelBuilder.Entity("Schedule.Domain.Entities.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealId"));

                    b.Property<string>("MealIngredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MealId");

                    b.ToTable("Meals", (string)null);
                });

            modelBuilder.Entity("Schedule.Domain.Entities.Day", b =>
                {
                    b.HasOne("Schedule.Domain.Entities.Meal", "Meal")
                        .WithMany("Day")
                        .HasForeignKey("AssignedMeal");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Schedule.Domain.Entities.Meal", b =>
                {
                    b.Navigation("Day");
                });
#pragma warning restore 612, 618
        }
    }
}
